version: "3"
services:
  flasky:
    image: ceph/ceph-daemon:latest-mimic
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          #memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - flasky
networks:
  flasky:
